#! /usr/bin/env python3

# This generates the header file containing file info
#  Since this information is almost static, let's just compile it into the program rather than having go find some other file and parse it
#  For a future flight you'll probably have to update a few variables down below

import ROOT
import os

if os.environ['PUEO_ROOT_DATA'] is None:
    print ("#error You gotta define PUEO_ROOT_DATA")

start_run = 783
end_run = 1402
pueo_flight=1


print(r"""#ifndef _PUEO$FLIGHT_RUN_INFOS_H
#define _PUEO$FLIGHT_RUN_INFOS_H

// Warning, this file is automatically generated.
// Beep boop.

#include <algorithm>

struct pueo$FLIGHT_runinfo {
  pueo$FLIGHT_runinfo(int run, int start, int end, int N )
       : run(run), start_time(start), end_time(end), nevents(N) {;}

  int run = 0;
  int start_time = 0;
  int end_time = 0;
  unsigned nevents = 0;
  bool operator<(const pueo$FLIGHT_runinfo & other) const { return end_time < other.end_time ; }
};

const pueo$FLIGHT_runinfo pueo$FLIGHT_flight[] =  {
""".replace("$FLIGHT",str(pueo_flight)))

num_runs = 0
for run in range(start_run, end_run+1):

    f = ROOT.TFile.Open("%s/run%d/headFile%d.root" % (os.environ['PUEO_ROOT_DATA'], run, run))
    if not f:
        continue
    t = f.Get('headerTree');
    if not t:
        continue
    N = t.GetEntries()
    if not N:
        continue

    start = t.GetMinimum("corrected_trigger_time.fSec")
    if start == 0:
        start = t.GetMinimum("triggerTime")
    if  start == 0:
        start = t.GetMinimum("readoutTime")
    end = t.GetMaximum("corrected_trigger_time.fSec")+1
    if end == 1:
        end = t.GetMaximum("triggerTime") + 1
    if end == 1:
        end = t.GetMaximum("readoutTime") + 1
    print (f"  pueo{pueo_flight}_runinfo ( {run}, {start}, {end}, {N} ),")
    num_runs += 1

print(r"""
};

const unsigned pueo$FLIGHT_num_runs = $NRUNS;

inline int pueo$FLIGHT_find_run(int t)
{
  pueo$FLIGHT_runinfo dummy ( 0,t,t,0);
  auto idx = std::upper_bound(pueo$FLIGHT_flight, pueo$FLIGHT_flight + pueo$FLIGHT_num_runs, dummy) - pueo$FLIGHT_flight;
  if (idx >= pueo$FLIGHT_num_runs)
  {
    return -1;
  }
  if (idx == 0 && t < pueo$FLIGHT_flight[0].start_time) return -1;
  return pueo$FLIGHT_flight[idx].run;
}


#endif""".replace("$FLIGHT",str(pueo_flight)).replace("$NRUNS", str(num_runs)))





